version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-aws-auditor"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18h75fcvn4ope"
s3_prefix = "sam-aws-auditor"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
